#ifndef HEADER_SM2_ERR_H
# define HEADER_SM2_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
void ERR_load_SM2_strings(void);
void ERR_unload_SM2_strings(void);
void ERR_SM2_error(int function, int reason, char *file, int line);
# define SM2err(f,r) ERR_SM2_error((f),(r),__FILE__,__LINE__)

/* Error codes for the SM2 functions. */
//TODO: complete it

/* Function codes. */
//TODO: complete it

/* Reason codes. */
//TODO: complete it

#ifdef  __cplusplus
}
#endif
#endif
